GET http://localhost:3000/users HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/users/create HTTP/1.1
Content-Type: application/json

{
    "name": "João",
    "password": "1234",
    "email": "joao@arbyte.com"
}

###
PUT http://localhost:3000/users/update/5f500e30480b9423fc9b1e8d HTTP/1.1
Content-Type: application/json

{
    "name": "João Victor",
    "password": "4321",
    "email": "victor@joao.com"
}

###
DELETE http://localhost:3000/users/delete/5f500e12480b9423fc9b1e8c HTTP/1.1
Content-Type: application/json
